name: gaze
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  bloc: ^8.1.2
  cupertino_icons: ^1.0.2
  cloud_firestore: ^4.9.1
  chewie: ^1.7.0
  dartz: ^0.10.1
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  firebase_core: ^2.15.1
  firebase_auth: ^4.9.0
  firebase_storage: ^11.2.6
  firebase_ui_auth: ^1.7.0
  font_awesome_flutter: ^10.5.0
  get_it: ^7.6.4
  iconly: ^1.0.1
  intl: ^0.18.1
  lottie: ^2.6.0
  path_provider: ^2.1.1
  provider: ^6.0.5
  shared_preferences: ^2.2.1
  smooth_page_indicator: ^1.1.0
  swipe_to: ^1.0.2
  url_launcher: ^6.1.14

dev_dependencies:
  flutter_test:
    sdk: flutter

  bloc_test: ^9.1.4
  flutter_lints: ^2.0.0
  firebase_auth_mocks: ^0.12.0
  fake_cloud_firestore: ^2.4.1+1
  firebase_storage_mocks: ^0.6.1
  google_sign_in_mocks: ^0.3.0
  mocktail: ^1.0.0
  very_good_analysis: ^5.1.0

flutter:

  uses-material-design: true

  fonts:
    - family: Aeonik
      fonts:
        - asset: assets/fonts/aeonik/AeonikTRIAL-Bold.otf
          weight: 700
        - asset: assets/fonts/aeonik/AeonikTRIAL-BoldItalic.otf
          style: italic
          weight: 700
        - asset: assets/fonts/aeonik/AeonikTRIAL-Light.otf
          weight: 300
        - asset: assets/fonts/aeonik/AeonikTRIAL-LightItalic.otf
          style: italic
          weight: 300
        - asset: assets/fonts/aeonik/AeonikTRIAL-Regular.otf
          weight: 400
        - asset: assets/fonts/aeonik/AeonikTRIAL-RegularItalic.otf
          style: italic
          weight: 400
    - family: Satisfy
      fonts:
        - asset: assets/fonts/satisfy/Satisfy-Regular.ttf
          weight: 400